#!/bin/bash

script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)

filter="$1"

cd $script_dir
scripts=$(find ./runs -maxdepth 1 -mindepth 1 -perm +0111 -type f)

for script in $scripts; do
    echo "Running $script"
    if echo "$script" | grep -qv "$filter"; then
        echo "Filtering $script"
        continue
    fi

    ./$script
done